# Generated by Django 3.1.5 on 2021-01-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocomp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='devicetype_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='manufacturer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='solutiontype_id',
            field=models.CharField(max_length=50),
        ),
    ]
